### ISSUE TITLE
docs throws an exception after enabling page translation

### ISSUE THREAD

**Issue by aiktb** [PlasmoHQ/docs#68]
I use page translation to view plasmo documents, but when I turn on page translation and browse multiple pages, the page will throw an exception, and I have to refresh the page to continue browsing the document.
I have this problem when translating web pages into Chinese or German.
Only Chrome's web translation causes the issue, Edge doesn't have the issue.

Can you try to fix this bug?
```txt
Application error: a client-side exception has occurred (see the browser console for more information).
```
![Snipaste_2023-08-01_19-52-11](https://github.com/PlasmoHQ/docs/assets/104723527/15083f9c-5ab0-41f3-a623-9ab2da572b7b)
```js
framework-0a897eab13466586.js:9 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at uH (https://docs.plasmo.com/_next/static/chunks/framework-0a897eab13466586.js:9:84988)
main-23c1aa3ceb058a6c.js:1 DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at uH (https://docs.plasmo.com/_next/static/chunks/framework-0a897eab13466586.js:9:84988)
main-23c1aa3ceb058a6c.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
```
![Snipaste_2023-08-01_19-54-17](https://github.com/PlasmoHQ/docs/assets/104723527/859938ad-9f8f-4af3-86bf-465d8996764d)

**Comment by louisgv** [comment]
Interesting... I wonder if there's a nextjs setting we can enable to prevent this type of behavior :-d...

**Comment by aiktb** [comment]
> Interesting... I wonder if there's a nextjs setting we can enable to prevent this type of behavior :-d...

It's strange, I try to deploy the main branch locally and on the [server](https://web.aiktb.com/framework), but I can't reproduce the bug, use the following command:
```bash
pnpm install
pnpm build
pnpm start --port=8080
```
Is there something wrong with the way I'm deploying?
Or maybe this is not a bug caused by React or Next programming, did you use the js/html Auto Minify function (provided by CDN)?

**Comment by louisgv** [comment]
@aiktb I don't think so. The docs is deployed on vercel :d.....
